export const SOCKET_DID_MOUNT = 'socket/SOCKET_DID_MOUNT'
export const SOCKET_CONNECT = 'socket/SOCKET_CONNECT'
export const SET_USERNAME = 'user/SET_USERNAME'
export const CHECK_USERNAME_AVAILABLE = 'user/CHECK_USERNAME_AVAILABLE'
