export const CREATE_BOARD = 'editor/CREATE_BOARD'
export const CREATE_NEW_BOARD = 'editor/CREATE_NEW_BOARD'
export const SELECT_HEX_TYPE = 'editor/SELECT_HEX_TYPE'
export const TOGGLE_MENU = 'editor/TOGGLE_MENU'
export const UPDATE_BOARD = 'editor/UPDATE_BOARD'
